services:
  app:
    build: .
    command: ["npm", "run", "start:dev"]
    env_file: .env
    restart: always
    depends_on:
      - redis
    ports:
      - '3003:3000'
    volumes:
      - ./:/app
      - ./templates:/templates
      - /app/node_modules
    
  redis:
    image: redis:alpine
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
