name: Release

on: workflow_dispatch

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm i

      - name: Set Git user to Actions Bot
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Run Release
        run: npx run release-it -- --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
